name: Deploy on push 
on:
 push:
   branches: [ main ]
   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
         key: ${{ secrets.EXPANSE_KEY }}
         name: id_rsa
         known_hosts: ${{ secrets.SSH_HOST }}
      -  name: Pull
         run: ssh scigap@login.expanse.sdsc.edu "cd /home/scigap/NeuroTest/sleep-stage-transition && /usr/bin/git pull origin main && cd /home/scigap/NeuroTest && sh copy.sh"
